### ISSUE TITLE
Issue with complex answers

### ISSUE THREAD

**Issue by matthewbarram** [n8henrie/alexa-wolfram-alpha#1]
Hi!

I noticed that if I make a request that seems to provide back a complex answer the echo will say there is a problem. But it can answer some simple things well. I think this could be the way strings are being parsed. Is this impacting others too?

Thanks 
Matthew

**Comment by matthewbarram** [comment]
This is caused by the request timing out, so in the lambda function I needed to extend the timeout.

**Comment by n8henrie** [comment]
Correct, I forgot to mention that I extended my timeout to 10 seconds (likely excessive). Will add to README, thanks.

**Comment by LordMelkor** [comment]
How do you increase the timeout? I don't see any parameters for it in the code...

**Comment by matthewbarram** [comment]
You can set it on the lambda function itself
