### ISSUE TITLE
errors trying to run

### ISSUE THREAD

**Issue by dfreelan** [n8henrie/alexa-wolfram-alpha#3]
right now when i run the skill on the echo, the echo tells me "there was a problem with the apps response"

When i test it on the AWS lambda management page, i get the error
```
{
  "errorMessage": "Handler 'handler' missing on module 'index'"
}
```

In the process of writing I double checked everything and can't figure out what I did wrong! any help on debugging would be appreciated. Very new to this process (i did set up ask-google)

Here's my setup (couldn't figure out where to put test_event.json, but everything else i think i followed correctly):

```
AWS lambda settings: 
  CODE:
     code entry type = edit code inline (copy pasted alex-wolfram-alpha.py)
     SKILL_ID = copy pasted from "application ID" from yhe developer console under my "wolfram" skill (looks like amzn1.ask.skill.######-#####-####-####-##########)
     WOLFRAM_ID = copy and pasted from wolfram app id. looks like ######-##########
  CONFIGURATION
      Runtime: Python 2.7
      Handler: index.handler
      Role: Choose an existing role
      Existing role: service-role/lambda_basic_execution
      timeout = 10 seconds

On the developer console:
   SKILL INFORMATION:
      Skill type: custom
      language: English US
      name: wolfram
      invocation name: wolfram  
      audio player: no
   INTERACTION MODEL:
      Intent Schema: copy pasted from intent_schema.json
      Sample Utterances: copy pasted from sample_utterances.txt
   CONFIGURATION:
      endpoint AWS lambraARN enabled
      geographical region = North America
      North America = arn:aws:lambda###########################
      Account Linking: no
      Permisions: nothing checked
    TEST
       Enabled
```

**Comment by dfreelan** [comment]
update: figured out there's a "service simulator" on the test page

testing the utterance "yo" returned the lambda response:
`"The remote endpoint could not be called, or the response it returned was invalid."`

**Comment by dfreelan** [comment]
Solved! 

i needed to change the handler from:  index.handler
to main.lambda_handler from the python code.

hope this helps future new people to figure this out.

**Comment by n8henrie** [comment]
Thanks for the update and glad you got it figured out. Sorry, but where is this `index.handler` you had to change? Is it somewhere in my code? I'm not seeing it.
